master:
  extends:
    file: conjur.yml
    service: conjur
  environment:
    CONJUR_MASTER_HOSTNAME: "conjur-master"
    CONJUR_MASTER_PASSWORD:
    CONJUR_MASTER_ORGACCOUNT: "docker-conjur"
    CONJUR_STANDBY_HOSTNAMES: "conjur-standby"
    CONJUR_FOLLOWER_HOSTNAMES: "conjur-follower"
    SEED_DIR: "/opt/conjur/seed"

standby:
  extends:
    file: conjur.yml
    service: conjur
  links:
    - master:conjur-master
  environment:
    CONJUR_STANDBY_HOSTNAME: "conjur-standby"
    SEED_DIR: "/opt/conjur/seed"

follower:
  extends:
    file: conjur.yml
    service: conjur
  links:
    - master:conjur-master
  environment:
    SEED_DIR: "/opt/conjur/seed"
    CONJUR_FOLLOWER_HOSTNAME: "conjur-follower"